language: generic

#Tells Travis we need super level permission
sudo: required
#Tell Travis we need docker pre-intsalled
services:
  - docker

#Series of setup before we either run tests or deploy
before_install:
  - docker build -t jchen96/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jchen96/docker-react npm run test